# Generated by Django 5.1.15 on 2026-06-19 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ArticleCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=120, unique=True, verbose_name="Название"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=140, unique=True, verbose_name="Слаг"
                    ),
                ),
            ],
            options={
                "verbose_name": "Рубрика статей",
                "verbose_name_plural": "Рубрики статей",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=220, verbose_name="Заголовок")),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=240, unique=True, verbose_name="Слаг"
                    ),
                ),
                (
                    "cover",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="articles/",
                        verbose_name="Обложка",
                    ),
                ),
                ("excerpt", models.TextField(blank=True, verbose_name="Анонс")),
                ("body", models.TextField(blank=True, verbose_name="Текст")),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="Опубликована"),
                ),
                ("published_at", models.DateField(verbose_name="Дата публикации")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создана"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлена"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="articles",
                        to="content.articlecategory",
                        verbose_name="Рубрика",
                    ),
                ),
            ],
            options={
                "verbose_name": "Статья",
                "verbose_name_plural": "Статьи",
                "ordering": ["-published_at", "-id"],
            },
        ),
    ]
