# Generated by Django 5.1.15 on 2026-06-19 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Lead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="Имя")),
                ("phone", models.CharField(max_length=40, verbose_name="Телефон")),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="E-mail"
                    ),
                ),
                ("message", models.TextField(blank=True, verbose_name="Сообщение")),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("contact_form", "Форма контактов"),
                            ("consultation", "Заказать консультацию"),
                            ("product", "Запрос цены (карточка товара)"),
                            ("solution", "Обсудить проект (решения)"),
                            ("other", "Другое"),
                        ],
                        default="contact_form",
                        max_length=20,
                        verbose_name="Источник",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "Новая"),
                            ("in_progress", "В работе"),
                            ("done", "Обработана"),
                            ("spam", "Спам"),
                        ],
                        default="new",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "page_url",
                    models.URLField(blank=True, verbose_name="Страница отправки"),
                ),
                (
                    "consent",
                    models.BooleanField(
                        default=True, verbose_name="Согласие на обработку ПДн"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Получена"),
                ),
                (
                    "related_product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="leads",
                        to="catalog.product",
                        verbose_name="Связанный товар",
                    ),
                ),
            ],
            options={
                "verbose_name": "Заявка",
                "verbose_name_plural": "Заявки",
                "ordering": ["-created_at"],
            },
        ),
    ]
