# Generated by Django 5.1.15 on 2026-06-19 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Advantage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.CharField(blank=True, max_length=8, verbose_name="Номер"),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Заголовок")),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "accent",
                    models.BooleanField(default=False, verbose_name="Красный акцент"),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="Порядок"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активно"),
                ),
            ],
            options={
                "verbose_name": "Преимущество",
                "verbose_name_plural": "Преимущества",
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="ClientLogo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="Клиент")),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="clients/",
                        verbose_name="Логотип",
                    ),
                ),
                ("url", models.URLField(blank=True, verbose_name="Ссылка")),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="Порядок"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
            ],
            options={
                "verbose_name": "Логотип клиента",
                "verbose_name_plural": "Логотипы клиентов",
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="HeroSlide",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.CharField(
                        blank=True,
                        help_text="например 01",
                        max_length=8,
                        verbose_name="Номер",
                    ),
                ),
                ("tag", models.CharField(max_length=120, verbose_name="Тег")),
                ("title", models.CharField(max_length=200, verbose_name="Заголовок")),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="hero/",
                        verbose_name="Изображение",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="Порядок"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
            ],
            options={
                "verbose_name": "Слайд hero",
                "verbose_name_plural": "Слайды hero",
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="PageContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.SlugField(
                        allow_unicode=True,
                        help_text="Стабильный идентификатор блока, напр. about.intro",
                        max_length=120,
                        unique=True,
                        verbose_name="Ключ",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        max_length=200, verbose_name="Название (для админки)"
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="Заголовок"
                    ),
                ),
                ("body", models.TextField(blank=True, verbose_name="Текст")),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлён"),
                ),
            ],
            options={
                "verbose_name": "Блок контента",
                "verbose_name_plural": "Контент страниц",
                "ordering": ["key"],
            },
        ),
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "company_name",
                    models.CharField(
                        default="QP Tool",
                        max_length=200,
                        verbose_name="Название компании",
                    ),
                ),
                (
                    "tagline",
                    models.CharField(
                        blank=True,
                        default="ОФИЦИАЛЬНЫЙ ПОСТАВЩИК · ЕКАТЕРИНБУРГ · С 2009",
                        max_length=200,
                        verbose_name="Слоган",
                    ),
                ),
                (
                    "phone_primary",
                    models.CharField(
                        blank=True, max_length=40, verbose_name="Основной телефон"
                    ),
                ),
                (
                    "phone_secondary",
                    models.CharField(
                        blank=True, max_length=40, verbose_name="Доп. телефон"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="E-mail"
                    ),
                ),
                ("address", models.TextField(blank=True, verbose_name="Адрес")),
                (
                    "work_hours",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="График работы"
                    ),
                ),
                (
                    "map_lat",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="Широта (карта)",
                    ),
                ),
                (
                    "map_lng",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="Долгота (карта)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Настройки сайта",
                "verbose_name_plural": "Настройки сайта",
            },
        ),
    ]
