# Generated by Django 5.1.15 on 2026-06-29 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("siteconfig", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="map_embed_url",
            field=models.TextField(
                blank=True,
                help_text="Вставьте код из Яндекс.Конструктора карт (тег <iframe …>) или прямую ссылку на карту-виджет.",
                verbose_name="Яндекс.Карта — код вставки или ссылка",
            ),
        ),
    ]
