# Generated by Django 5.1.15 on 2026-07-02 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("siteconfig", "0002_sitesettings_map_embed_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="about_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="site/",
                verbose_name="Фото на странице «О компании»",
            ),
        ),
    ]
